### ISSUE TITLE
Emotion Model Performance 

### ISSUE THREAD

**Issue by TuhinShahin** [asaugat04/Mood-Melody#1]
You can add your own dataset rather then using the FER data and in the preprocessing of the data you can assure of accuracy of over 80%. I you wish I have some guideline for you in image preprocessing and some image totaling of around 60k labeled image. 
I found your project interesting in terms of music according to images. Give me a knock if you have interest on the data as well.

**Comment by asaugat04** [comment]
Thank you so much for your kind offer and for recognizing the potential in our project. It was a passion project for my final year, and although I'm unable to take it further right now, I'm genuinely interested in exploring this collaboration in the future. Your contribution could be a significant addition. Let's definitely keep in touch, and I hope to revisit this project when the time allows. Thank you again for reaching out!
